# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [Hansanghyeon/issue*]

jobs:
  build:
    runs-on: ubuntu-latest
    # if: ${{ github.event.repository.owner.name == 'beeclover' }}
    steps:
      - uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "##[set-output name=id;]$(echo ${GITHUB_REF#refs/heads/Hansanghyeon/issue})"
        id: extract_branch
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "" # If blank, default: triggered branch
          destination_branch: "develop" # If blank, default: master
          pr_title: "${{ steps.extract_branch.outputs.branch }}" # Title of pull request
          pr_body: ":crown: *An automated PR*\nResolves: #${{steps.extract_branch.outputs.id}}" # Full markdown support, requires pr_title to be set
          pr_draft: true # Creates pull request as draft
          github_token: ${{ secrets.TOKEN }}
