# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [Hansanghyeon/issue*]

jobs:
  build:
    runs-on: ubuntu-latest
    # if: ${{ github.event.repository.owner.name == 'beeclover' }}
    steps:
      - name: Extract branch name
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "##[set-output name=id;]$(echo ${GITHUB_REF#refs/heads/Hansanghyeon/issue})"
        id: extract_branch
      - name: Create status check
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          RES_CODE=$(curl \
          -X POST \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          -o /dev/null -w "%{http_code}" \
          https://api.github.com/repos/${{github.event.repository.owner.name}}/${{github.event.repository.name}}/pulls/${{steps.extract_branch.outputs.id}});
          echo $RES_CODE;
      - uses: actions/checkout@v2
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "" # If blank, default: triggered branch
          destination_branch: "develop" # If blank, default: master
          pr_title: "${{ steps.extract_branch.outputs.branch }}" # Title of pull request
          pr_body: "Resolves: #${{steps.extract_branch.outputs.id}}\n\n:crown: *An automated PR*" # Full markdown support, requires pr_title to be set
          pr_draft: true # Creates pull request as draft
          github_token: ${{ secrets.TOKEN }}
